### ISSUE TITLE
Is trial version of Understand supported?

### ISSUE THREAD

**Issue by vchong** [league1991/CodeAtlasSublime#2]
When clicking 'Start Atlas', python seems to have some error:

```
C:\Users\foo\AppData\Roaming\Sublime Text 3\Packages\CodeAtlas>cd ./CodeViewPy

C:\Users\foo\AppData\Roaming\Sublime Text 3\Packages\CodeAtlas\CodeViewPy>python
 main.py 12346
argv: ['main.py', '12346']
<bound signal updateSignal of SceneUpdateThread object at 0x00000000037593A8>
main
```

Then, when Open DB, python says no config file:

```
no config file: C:/Users/foo/AppData/Roaming/Sublime Text 3/Packages/CodeAtlas/C
odeAtlasSublime.udb.config
```

python and PyQt are installed using the 64-bit versions.
Understand Trial version 5.0.930
Sublime Text Build 3143

Thanks

**Comment by vchong** [comment]
Restarted Sublime Text and it seemed like the config file was automatically generated? I can see some functions in the Code Atlas window now, although nothing as pretty as your examples. ;)

**Comment by league1991** [comment]
@vchong  The config file is used to record your data, such as the graph on viewport, so that next time you open the database, the previous graph will be displayed on viewport. That's why the config file will be generated automatically when you close the plugin.

**Comment by HBouch** [comment]
Hey, I restarted Sublime, it created the config file, but can't see anything in the graph ... Is it necessary to have 32 versions of everything ?
